// Auto-generated by generate-voiceover.py — do not edit manually.
// Re-run `python3 generate-voiceover.py --force` to update.

import type { SceneId } from "./voiceover-config";

export type SceneTiming = {
  durationFrames: number;
  /** Frame offset within the scene at which each phrase starts. */
  phraseOffsets: number[];
};

export const VOICEOVER_TIMINGS: Record<SceneId, SceneTiming> = {
  "act1": {
    "durationFrames": 503,
    "phraseOffsets": [
      0
    ]
  },
  "act2a": {
    "durationFrames": 896,
    "phraseOffsets": [
      0,
      187,
      575,
      668
    ]
  },
  "act2b": {
    "durationFrames": 643,
    "phraseOffsets": [
      0,
      277
    ]
  },
  "act3": {
    "durationFrames": 937,
    "phraseOffsets": [
      0,
      209,
      491,
      740,
      828
    ]
  },
  "act4": {
    "durationFrames": 255,
    "phraseOffsets": [
      0,
      86,
      138,
      198
    ]
  },
  "act5": {
    "durationFrames": 573,
    "phraseOffsets": [
      0,
      169,
      434
    ]
  },
  "act6": {
    "durationFrames": 551,
    "phraseOffsets": [
      0,
      311
    ]
  },
  "closing": {
    "durationFrames": 114,
    "phraseOffsets": [
      0
    ]
  }
};
