// Auto-generated by generate-voiceover.py. Do not edit manually.
// Re-run `python3 generate-voiceover.py --force` to update.

import type { SceneId } from "./voiceover-config";

export type SceneTiming = {
  durationFrames: number;
  /** Frame offset within the scene at which each phrase starts. */
  phraseOffsets: number[];
};

export const VOICEOVER_TIMINGS: Record<SceneId, SceneTiming> = {
  "problem": {
    "durationFrames": 721,
    "phraseOffsets": [
      0
    ]
  },
  "demo": {
    "durationFrames": 2756,
    "phraseOffsets": []
  },
  "coach-builder": {
    "durationFrames": 703,
    "phraseOffsets": [
      0,
      187,
      605
    ]
  },
  "prefs-memory": {
    "durationFrames": 1026,
    "phraseOffsets": [
      0,
      420,
      701,
      877
    ]
  },
  "mobile": {
    "durationFrames": 535,
    "phraseOffsets": [
      0,
      172
    ]
  },
  "architecture": {
    "durationFrames": 753,
    "phraseOffsets": [
      0,
      281
    ]
  },
  "closing": {
    "durationFrames": 123,
    "phraseOffsets": [
      0
    ]
  }
};
